version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  your_app_1:
    image: mrudnicki123/amazon-demo:latest
    container_name: your_app_1
    expose:
      - "8000"

  your_app_2:
    image: mrudnicki123/amazon-demo:latest
    container_name: your_app_2
    expose:
      - "8000"

  your_app_3:
    image: mrudnicki123/amazon-demo:latest
    container_name: your_app_3
    expose:
      - "8000"